### ISSUE TITLE
Sample StoreCredentialApp fails to launch on macOS : 

### ISSUE THREAD

**Issue by marcpaquette-acceo** [microsoft/credential-secure-storage-for-java#12]
When I try to execute the sample application on macOS, I get a ClassNotFoundException.

Steps I did:
* fetched current repo (1.0.1-SNAPSHOT)
* compiled the project (mvn clean verify) without errors on macOS using OpenJDK 21.0.3 from Microsoft and maven 3.9.8 
* when into sample and compiled it (mvn clean package), no errors
* copied dependencies into a new directory under sample/libs (including credential-secure-storage-1.0.1-SNAPSHOT.jar)
* tried to run the sample providing the class path at command-line, as seen below:

````
[marcpa@DeBeauvoir sample]$ pwd
/Users/marcpa/Code/credential-secure-storage-for-java/sample
[marcpa@DeBeauvoir sample]$ ls libs
credential-secure-storage-1.0.1-SNAPSHOT.jar    slf4j-api-1.7.36.jar
jna-platform-5.9.0.jar                          slf4j-jdk14-1.7.36.jar
[marcpa@DeBeauvoir sample]$ java -cp libs/*:target/credential-secure-storage-sample-1.0.0.jar com.microsoft.credentialstorage.sample.StoredCredentialApp
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/win32/StdCallLibrary
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at com.microsoft.credentialstorage.StorageProvider.<clinit>(StorageProvider.java:74)
        at com.microsoft.credentialstorage.sample.StoredCredentialApp.run(StoredCredentialApp.java:30)
        at com.microsoft.credentialstorage.sample.StoredCredentialApp.main(StoredCredentialApp.java:25)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.win32.StdCallLibrary
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 12 more
[marcpa@DeBeauvoir sample]$ 
````

Some thoughts, in case it could help : 

It seems that StorageProvider loads CredManagerBackedSecureStore in a static block to see if it is supported, but that tries to pull up some dependencies that are not available on current platform (macOS). Looks like a catch-22 situation.

I guess one way out of this would be to define a separate class for the `isSupported()` methods, probably adding a parameter for the secure store kind checked; downside is that adds another class with some sort of global knowledge about all secure store providers.

Another possibility would be to have a separate class for each secure store (CredManagerBackedSecureStoreSupport, KeychainSecurityCliStoreSupport, etc) where the `isSupported()` methods are implemented, without any of them depending on platform-specific classes. This way, StorageProvider will be able to call every `isSupported()` without any chance of getting a class not found.

**Comment by marcpaquette-acceo** [comment]
It turns out I was missing one jar, jna-5.9.0.jar. My bad.
Producing an "executable" jar for sample with maven-shade-plugin would prevent such issues, or simply mentioning the list of jars in a readme... 
Anyway, I'm closing the issue as there is no real issue here.
Thanks for your work !
